# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# See https://github.com/earthobservations/wetterdienst for implementation

# Required
version: 2

# Using test server while Python 3.9 not supported
# https://github.com/readthedocs/readthedocs-docker-images/pull/159#issuecomment-785048185
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build documentation for mkdocs
mkdocs:
  configuration: mkdocs.yml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs-requirements.txt