dist: xenial
language: python
python:
  - 3.8
  - 3.9
# command to install dependencies
before_install:
  - sudo apt-get update
  - curl -sSL https://install.python-poetry.org | python3 -
install:
  - poetry install -vv
  - poetry shell
# command to run tests
script:
  - pytest